let configure error if using --with-pam but pam cannot compile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23547,8 +23547,6 @@ fi
 
 
 
-
-
 # Check whether --with-xauth or --without-xauth was given.
 if test "${with_xauth+set}" = set; then
   withval="$with_xauth"
@@ -29559,6 +29557,11 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
+if test "$tac_pam_get_user_2nd_arg" = "none" && test "$pammoddir" != "disabled" ;then
+  { { echo "$as_me:$LINENO: error: Unable to compile PAM bits, missing pam-devel?" >&5
+echo "$as_me: error: Unable to compile PAM bits, missing pam-devel?" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 
