move linux/cpuset.c -> linux/cpuset/cpuset.c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT program_prefix program_suffix PBS_MACH INCLUDE_SERVER_TRUE INCLUDE_SERVER_FALSE INCLUDE_MOM_TRUE INCLUDE_MOM_FALSE INCLUDE_CLIENTS_TRUE INCLUDE_CLIENTS_FALSE INCLUDE_DRMAA_TRUE INCLUDE_DRMAA_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP AR LN_S ECHO ac_ct_AR RANLIB ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LEX LEXLIB LEX_OUTPUT_ROOT YACC TBL PIC ROFF PBSPOE PBSPOEO BUILDCPA_TRUE BUILDCPA_FALSE MOMLIBS SCHD_TYPE_SUBDIR SCHD_TYPE SCHD_BASL_TRUE SCHD_BASL_FALSE SCHD_LIBS SCHD_CODE USING_RPP_TRUE USING_RPP_FALSE USING_SYSLOG_TRUE USING_SYSLOG_FALSE PBS_SERVER_HOME PBS_DEFAULT_FILE PBS_DEFAULT_SERVER PBS_ENVIRON RCP_PATH RCP_ARGS RSH_PATH INCLUDE_MOM_RCP_TRUE INCLUDE_MOM_RCP_FALSE SENDMAIL_CMD pammoddir INCLUDE_PAM_TRUE INCLUDE_PAM_FALSE xauth_path CYGPATH TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_LIBS TCL_DEFS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_SHLIB_LD_LIBS TCL_INCLUDES tclx_VERSION tclx_SRC_DIR tclx_LIB_FILE tclx_LIB_SPEC tclx_STUB_LIB_FILE tclx_STUB_LIB_SPEC tclx_STUB_LIB_PATH TK_VERSION TK_BIN_DIR TK_SRC_DIR TK_LIB_FILE TK_LIB_FLAG TK_LIB_SPEC TK_STUB_LIB_FILE TK_STUB_LIB_FLAG TK_STUB_LIB_SPEC TK_LIBS TK_XINCLUDES TK_INCLUDES tkx_VERSION tkx_SRC_DIR tkx_LIB_FILE tkx_LIB_SPEC tkx_STUB_LIB_FILE tkx_STUB_LIB_SPEC tkx_STUB_LIB_PATH INCLUDE_GUI_TRUE INCLUDE_GUI_FALSE MY_TCL_LIBS MY_TCL_INCS MY_TCLTK_LIBS MY_TCLTK_INCS USING_TCL_TRUE USING_TCL_FALSE USING_TK_TRUE USING_TK_FALSE TCLSH_PROG WISH_PROG EXTRA_QSTAT_LIBS USE_TCLQSTAT_TRUE USE_TCLQSTAT_FALSE READLINE_LIBS GPERF HAVE_DOT DOXYGEN acx_pthread_config PTHREAD_LIBS PTHREAD_CFLAGS DRMAA_DOCS_TRUE DRMAA_DOCS_FALSE GENERIC_CONFIG spec_name spec_version spec_snap LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os MAKE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT program_prefix program_suffix PBS_MACH INCLUDE_SERVER_TRUE INCLUDE_SERVER_FALSE INCLUDE_MOM_TRUE INCLUDE_MOM_FALSE INCLUDE_CLIENTS_TRUE INCLUDE_CLIENTS_FALSE INCLUDE_DRMAA_TRUE INCLUDE_DRMAA_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP AR LN_S ECHO ac_ct_AR RANLIB ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LEX LEXLIB LEX_OUTPUT_ROOT YACC TBL PIC ROFF PBSPOE PBSPOEO BUILD_L26_CPUSETS_TRUE BUILD_L26_CPUSETS_FALSE BUILDCPA_TRUE BUILDCPA_FALSE MOMLIBS SCHD_TYPE_SUBDIR SCHD_TYPE SCHD_BASL_TRUE SCHD_BASL_FALSE SCHD_LIBS SCHD_CODE USING_RPP_TRUE USING_RPP_FALSE USING_SYSLOG_TRUE USING_SYSLOG_FALSE PBS_SERVER_HOME PBS_DEFAULT_FILE PBS_DEFAULT_SERVER PBS_ENVIRON RCP_PATH RCP_ARGS RSH_PATH INCLUDE_MOM_RCP_TRUE INCLUDE_MOM_RCP_FALSE SENDMAIL_CMD pammoddir INCLUDE_PAM_TRUE INCLUDE_PAM_FALSE xauth_path CYGPATH TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_LIBS TCL_DEFS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_SHLIB_LD_LIBS TCL_INCLUDES tclx_VERSION tclx_SRC_DIR tclx_LIB_FILE tclx_LIB_SPEC tclx_STUB_LIB_FILE tclx_STUB_LIB_SPEC tclx_STUB_LIB_PATH TK_VERSION TK_BIN_DIR TK_SRC_DIR TK_LIB_FILE TK_LIB_FLAG TK_LIB_SPEC TK_STUB_LIB_FILE TK_STUB_LIB_FLAG TK_STUB_LIB_SPEC TK_LIBS TK_XINCLUDES TK_INCLUDES tkx_VERSION tkx_SRC_DIR tkx_LIB_FILE tkx_LIB_SPEC tkx_STUB_LIB_FILE tkx_STUB_LIB_SPEC tkx_STUB_LIB_PATH INCLUDE_GUI_TRUE INCLUDE_GUI_FALSE MY_TCL_LIBS MY_TCL_INCS MY_TCLTK_LIBS MY_TCLTK_INCS USING_TCL_TRUE USING_TCL_FALSE USING_TK_TRUE USING_TK_FALSE TCLSH_PROG WISH_PROG EXTRA_QSTAT_LIBS USE_TCLQSTAT_TRUE USE_TCLQSTAT_FALSE READLINE_LIBS GPERF HAVE_DOT DOXYGEN acx_pthread_config PTHREAD_LIBS PTHREAD_CFLAGS DRMAA_DOCS_TRUE DRMAA_DOCS_FALSE GENERIC_CONFIG spec_name spec_version spec_snap LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -21775,6 +21775,7 @@ if test "${enable_cpuset+set}" = set; then
   enableval="$enable_cpuset"
 
 fi;
+build_l26_cpuset=no
 if test "x$enable_cpuset" != "xno" ;then
   echo "$as_me:$LINENO: checking for cpuset_cpus_weight in -lcpuset" >&5
 echo $ECHO_N "checking for cpuset_cpus_weight in -lcpuset... $ECHO_C" >&6
@@ -21906,7 +21907,8 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_bitmask_bitmask_alloc" >&5
 echo "${ECHO_T}$ac_cv_lib_bitmask_bitmask_alloc" >&6
 if test $ac_cv_lib_bitmask_bitmask_alloc = yes; then
-  MOMLIBS="$MOMLIBS -lcpuset -lbitmask"
+  build_l26_cpuset=yes
+       MOMLIBS="$MOMLIBS -lcpuset -lbitmask"
 
 cat >>confdefs.h <<\_ACEOF
 #define PENABLE_LINUX26_CPUSETS 1
@@ -21919,6 +21921,16 @@ fi
 fi
 
 fi
+
+
+if test "$build_l26_cpuset" = yes; then
+  BUILD_L26_CPUSETS_TRUE=
+  BUILD_L26_CPUSETS_FALSE='#'
+else
+  BUILD_L26_CPUSETS_TRUE='#'
+  BUILD_L26_CPUSETS_FALSE=
+fi
+
 
 
 # Check whether --enable-array or --disable-array was given.
@@ -33985,7 +33997,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
-                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ac_config_files="$ac_config_files buildutils/pbs_mkdirs buildutils/self-extract-head-sh Makefile torque.spec doc/Makefile doc/man1/Makefile doc/man3/Makefile doc/man7/Makefile doc/man8/Makefile src/Makefile src/cmds/Makefile src/iff/Makefile src/gui/Makefile src/gui/Ccode/Makefile src/include/Makefile src/lib/Makefile src/lib/Libattr/Makefile src/lib/Libcmds/Makefile src/lib/Libdis/Makefile src/lib/Libifl/Makefile src/lib/Liblog/Makefile src/lib/Libnet/Makefile src/lib/Libpbs/Makefile src/lib/Libsite/Makefile src/mom_rcp/Makefile src/resmom/Makefile src/resmom/aix4/Makefile src/resmom/aix5/Makefile src/resmom/darwin/Makefile src/resmom/digitalunix/Makefile src/resmom/freebsd/Makefile src/resmom/freebsd5/Makefile src/resmom/fujitsu/Makefile src/resmom/hpux10/Makefile src/resmom/hpux11/Makefile src/resmom/irix5/Makefile src/resmom/irix6/Makefile src/resmom/irix6array/Makefile src/resmom/linux/Makefile src/resmom/netbsd/Makefile src/resmom/solaris5/Makefile src/resmom/solaris7/Makefile src/resmom/sunos4/Makefile src/resmom/unicos8/Makefile src/resmom/unicosmk2/Makefile src/resmom/cpa/Makefile src/scheduler.basl/Makefile src/scheduler.cc/Makefile src/scheduler.cc/samples/Makefile src/scheduler.cc/samples/cray_t3e/Makefile src/scheduler.cc/samples/dec_cluster/Makefile src/scheduler.cc/samples/fifo/Makefile src/scheduler.cc/samples/msic_cluster/Makefile src/scheduler.cc/samples/sgi_origin/Makefile src/scheduler.cc/samples/umn_cluster/Makefile src/scheduler.tcl/Makefile src/server/Makefile src/tools/Makefile src/tools/xpbsmon/Makefile src/drmaa/Makefile src/drmaa/src/Makefile src/drmaa/test/Makefile src/drmaa/Doxyfile src/pam/Makefile"
+                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ac_config_files="$ac_config_files buildutils/pbs_mkdirs buildutils/self-extract-head-sh Makefile torque.spec doc/Makefile doc/man1/Makefile doc/man3/Makefile doc/man7/Makefile doc/man8/Makefile src/Makefile src/cmds/Makefile src/iff/Makefile src/gui/Makefile src/gui/Ccode/Makefile src/include/Makefile src/lib/Makefile src/lib/Libattr/Makefile src/lib/Libcmds/Makefile src/lib/Libdis/Makefile src/lib/Libifl/Makefile src/lib/Liblog/Makefile src/lib/Libnet/Makefile src/lib/Libpbs/Makefile src/lib/Libsite/Makefile src/mom_rcp/Makefile src/resmom/Makefile src/resmom/aix4/Makefile src/resmom/aix5/Makefile src/resmom/darwin/Makefile src/resmom/digitalunix/Makefile src/resmom/freebsd/Makefile src/resmom/freebsd5/Makefile src/resmom/fujitsu/Makefile src/resmom/hpux10/Makefile src/resmom/hpux11/Makefile src/resmom/irix5/Makefile src/resmom/irix6/Makefile src/resmom/irix6array/Makefile src/resmom/linux/Makefile src/resmom/linux/cpuset/Makefile src/resmom/netbsd/Makefile src/resmom/solaris5/Makefile src/resmom/solaris7/Makefile src/resmom/sunos4/Makefile src/resmom/unicos8/Makefile src/resmom/unicosmk2/Makefile src/resmom/cpa/Makefile src/scheduler.basl/Makefile src/scheduler.cc/Makefile src/scheduler.cc/samples/Makefile src/scheduler.cc/samples/cray_t3e/Makefile src/scheduler.cc/samples/dec_cluster/Makefile src/scheduler.cc/samples/fifo/Makefile src/scheduler.cc/samples/msic_cluster/Makefile src/scheduler.cc/samples/sgi_origin/Makefile src/scheduler.cc/samples/umn_cluster/Makefile src/scheduler.tcl/Makefile src/server/Makefile src/tools/Makefile src/tools/xpbsmon/Makefile src/drmaa/Makefile src/drmaa/src/Makefile src/drmaa/test/Makefile src/drmaa/Doxyfile src/pam/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -34130,6 +34142,13 @@ if test -z "${am__fastdepCXX_TRUE}" && test -z "${am__fastdepCXX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_L26_CPUSETS_TRUE}" && test -z "${BUILD_L26_CPUSETS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_L26_CPUSETS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_L26_CPUSETS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -34693,6 +34712,7 @@ do
   "src/resmom/irix6/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/resmom/irix6/Makefile" ;;
   "src/resmom/irix6array/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/resmom/irix6array/Makefile" ;;
   "src/resmom/linux/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/resmom/linux/Makefile" ;;
+  "src/resmom/linux/cpuset/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/resmom/linux/cpuset/Makefile" ;;
   "src/resmom/netbsd/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/resmom/netbsd/Makefile" ;;
   "src/resmom/solaris5/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/resmom/solaris5/Makefile" ;;
   "src/resmom/solaris7/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/resmom/solaris7/Makefile" ;;
@@ -34894,6 +34914,8 @@ s,@PIC@,$PIC,;t t
 s,@ROFF@,$ROFF,;t t
 s,@PBSPOE@,$PBSPOE,;t t
 s,@PBSPOEO@,$PBSPOEO,;t t
+s,@BUILD_L26_CPUSETS_TRUE@,$BUILD_L26_CPUSETS_TRUE,;t t
+s,@BUILD_L26_CPUSETS_FALSE@,$BUILD_L26_CPUSETS_FALSE,;t t
 s,@BUILDCPA_TRUE@,$BUILDCPA_TRUE,;t t
 s,@BUILDCPA_FALSE@,$BUILDCPA_FALSE,;t t
 s,@MOMLIBS@,$MOMLIBS,;t t
