b - be more careful about broken tclx installs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23673,7 +23673,7 @@ if test "${TCL}" = "1" -a "x${with_tclx}" != "xno" ; then
 		with_tclx=""
 		user_requested_tclx=yes
 	fi
-	# find and load tclxConfig.sh
+	# find and load tclxConfig.sh which only exists for older versions
 
     #
     # Ok, lets find the tclx configuration
@@ -23767,9 +23767,7 @@ echo "${ECHO_T}found $tclx_BIN_DIR/tclxConfig.sh" >&6
 	fi
     fi
 
-        if test "x$tclx_BIN_DIR" = "xnone" ; then
-          TCLX=0
-        else
+        if test "x$tclx_BIN_DIR" != "xnone" ; then
 
     echo "$as_me:$LINENO: checking for existence of ${tclx_BIN_DIR}/tclxConfig.sh" >&5
 echo $ECHO_N "checking for existence of ${tclx_BIN_DIR}/tclxConfig.sh... $ECHO_C" >&6
@@ -23810,8 +23808,156 @@ echo "$as_me: WARNING: Found Makefile - using build library specs for tclx" >&2;
 
 
 
-	  TCLX=1
         fi
+
+        orig_CFLAGS="$CFLAGS"
+        CFLAGS="$TCL_INCLUDES"
+        if test "${ac_cv_header_tclExtend_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for tclExtend.h" >&5
+echo $ECHO_N "checking for tclExtend.h... $ECHO_C" >&6
+if test "${ac_cv_header_tclExtend_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_tclExtend_h" >&5
+echo "${ECHO_T}$ac_cv_header_tclExtend_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking tclExtend.h usability" >&5
+echo $ECHO_N "checking tclExtend.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <tclExtend.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking tclExtend.h presence" >&5
+echo $ECHO_N "checking tclExtend.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <tclExtend.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: tclExtend.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: tclExtend.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tclExtend.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: tclExtend.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: tclExtend.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: tclExtend.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tclExtend.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: tclExtend.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tclExtend.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: tclExtend.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tclExtend.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: tclExtend.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tclExtend.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: tclExtend.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tclExtend.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: tclExtend.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------- ##
+## Report this to torqueusers@supercluster.org ##
+## ------------------------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for tclExtend.h" >&5
+echo $ECHO_N "checking for tclExtend.h... $ECHO_C" >&6
+if test "${ac_cv_header_tclExtend_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_tclExtend_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_tclExtend_h" >&5
+echo "${ECHO_T}$ac_cv_header_tclExtend_h" >&6
+
+fi
+if test $ac_cv_header_tclExtend_h = yes; then
+  TCLX=1
+else
+  TCLX=0
+fi
+
+
+        CFLAGS="$orig_CFLAGS"
+
 	if test "x$user_requested_tclx" = "xyes" -a $TCLX = 0 ;then
           { { echo "$as_me:$LINENO: error: TclX was requested but not found" >&5
 echo "$as_me: error: TclX was requested but not found" >&2;}
@@ -24258,34 +24404,37 @@ fi
 
 if test "${TCL}" = "1"; then
   # try to hack in a run-time search path if needed
-  orig_MY_TCL_LIBS="$MY_TCL_LIBS"
+
+
   orig_libdir="$libdir"
-  MY_TCL_LIBS=""
-  for tcllib_part in $orig_MY_TCL_LIBS ;do
-    case $tcllib_part in
+  t_add_rpath_libs=""
+  for lib_part in $MY_TCL_LIBS ;do
+    case $lib_part in
       -L/*)
-        tcllibdir=`echo $tcllib_part | sed s/-L//`
-        tcldir_in_syslib_path=no
+        t_libdir=`echo $lib_part | sed s/-L//`
+        t_dir_in_syslib_path=no
         for sysdir in $sys_lib_dlsearch_path_spec ;do
-           if test "X$tcllibdir" = "X$sysdir" ;then
-               tcldir_in_syslib_path=yes
+           if test "X$t_libdir" = "X$sysdir" ;then
+               t_dir_in_syslib_path=yes
                break
            fi
         done
-        MY_TCL_LIBS="${MY_TCL_LIBS} ${tcllib_part}"
-        if test "X$tcldir_in_syslib_path" = "Xno" ;then
-           libdir="$tcllibdir"
+        t_add_rpath_libs="${t_add_rpath_libs} ${lib_part}"
+        if test "X$t_dir_in_syslib_path" = "Xno" ;then
+           libdir="$t_libdir"
            eval "new_lib_spec=\"$hardcode_libdir_flag_spec\""
-           MY_TCL_LIBS="${MY_TCL_LIBS} ${new_lib_spec}"
+           t_add_rpath_libs="${t_add_rpath_libs} ${new_lib_spec}"
         fi
         ;;
       -L)
         ;;
-      *) MY_TCL_LIBS="${MY_TCL_LIBS} ${tcllib_part}"
+      *) t_add_rpath_libs="${t_add_rpath_libs} ${lib_part}"
         ;;
     esac
   done
   libdir="$orig_libdir"
+  MY_TCL_LIBS="$t_add_rpath_libs"
+
 
   orig_LIBS="$LIBS"
   orig_CFLAGS="$CFLAGS"
@@ -24402,34 +24551,37 @@ fi
 
 if test "${TK}" = "1"; then
   # try to hack in a run-time search path if needed
-  orig_MY_TCLTK_LIBS="$MY_TCLTK_LIBS"
+
+
   orig_libdir="$libdir"
-  MY_TCLTK_LIBS=""
-  for tcllib_part in $orig_MY_TCLTK_LIBS ;do
-    case $tcllib_part in
+  t_add_rpath_libs=""
+  for lib_part in $MY_TCLTK_LIBS ;do
+    case $lib_part in
       -L/*)
-        tcllibdir=`echo $tcllib_part | sed s/-L//`
-        tcldir_in_syslib_path=no
+        t_libdir=`echo $lib_part | sed s/-L//`
+        t_dir_in_syslib_path=no
         for sysdir in $sys_lib_dlsearch_path_spec ;do
-           if test "X$tcllibdir" = "X$sysdir" ;then
-               tcldir_in_syslib_path=yes
+           if test "X$t_libdir" = "X$sysdir" ;then
+               t_dir_in_syslib_path=yes
                break
            fi
         done
-        MY_TCLTK_LIBS="${MY_TCLTK_LIBS} ${tcllib_part}"
-        if test "X$tcldir_in_syslib_path" = "Xno" ;then
-           libdir="$tcllibdir"
+        t_add_rpath_libs="${t_add_rpath_libs} ${lib_part}"
+        if test "X$t_dir_in_syslib_path" = "Xno" ;then
+           libdir="$t_libdir"
            eval "new_lib_spec=\"$hardcode_libdir_flag_spec\""
-           MY_TCLTK_LIBS="${MY_TCLTK_LIBS} ${new_lib_spec}"
+           t_add_rpath_libs="${t_add_rpath_libs} ${new_lib_spec}"
         fi
         ;;
       -L)
         ;;
-      *) MY_TCLTK_LIBS="${MY_TCLTK_LIBS} ${tcllib_part}"
+      *) t_add_rpath_libs="${t_add_rpath_libs} ${lib_part}"
         ;;
     esac
   done
   libdir="$orig_libdir"
+  MY_TCLTK_LIBS="$t_add_rpath_libs"
+
 
   orig_LIBS="$LIBS"
   orig_CFLAGS="$CFLAGS"
