configure fixes for linux x86_64 and tcl install weirdness (USC)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -812,6 +812,249 @@ fi
 
 
 
+user_set_cc_val=no
+
+# Check whether --set-cc was given.
+if test "${set_cc+zzq}" = zzq; then
+  setval="$set_cc"
+  CC="${setval}"; user_set_cc_val=yes
+fi
+test "$CC" = yes && { CC=cc; user_set_cc_val=no; }
+
+
+# Check whether --set-cflags was given.
+if test "${set_cflags+zzq}" = zzq; then
+  setval="$set_cflags"
+  cflags="${setval}"
+else
+  cflags="not_set"
+fi
+test "$cflags" = yes && cflags=""
+
+test "$cflags" = not_set || CFLAGS="$cflags"
+pbs_save_CFLAGS="$CFLAGS"
+# Extract the first word of "gcc", so it can be a program name with args.
+set dummy gcc; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:2277: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$CC"; then
+  ac_cv_prog_CC="$CC" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+  for ac_dir in $PATH; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_CC="gcc"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+CC="$ac_cv_prog_CC"
+if test -n "$CC"; then
+  echo "$ac_t""$CC" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test -z "$CC"; then
+  # Extract the first word of "cc", so it can be a program name with args.
+set dummy cc; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:2306: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$CC"; then
+  ac_cv_prog_CC="$CC" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+  ac_prog_rejected=no
+  for ac_dir in $PATH; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      if test "$ac_dir/$ac_word" = "/usr/ucb/cc"; then
+        ac_prog_rejected=yes
+	continue
+      fi
+      ac_cv_prog_CC="cc"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+if test $ac_prog_rejected = yes; then
+  # We found a bogon in the path, so make sure we never use it.
+  set dummy $ac_cv_prog_CC
+  shift
+  if test $# -gt 0; then
+    # We chose a different compiler from the bogus one.
+    # However, it has the same basename, so the bogon will be chosen
+    # first if we set CC to just the basename; use the full file name.
+    shift
+    set dummy "$ac_dir/$ac_word" "$@"
+    shift
+    ac_cv_prog_CC="$@"
+  fi
+fi
+fi
+fi
+CC="$ac_cv_prog_CC"
+if test -n "$CC"; then
+  echo "$ac_t""$CC" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+  test -z "$CC" && { echo "configure: error: no acceptable cc found in \$PATH" 1>&2; exit 1; }
+fi
+
+echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works""... $ac_c" 1>&6
+echo "configure:2354: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
+
+ac_ext=c
+# CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='${CC-cc} -c $CFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
+ac_link='${CC-cc} -o conftest $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+cross_compiling=$ac_cv_prog_cc_cross
+
+cat > conftest.$ac_ext <<EOF
+#line 2364 "configure"
+#include "confdefs.h"
+main(){return(0);}
+EOF
+if { (eval echo configure:2368: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+  ac_cv_prog_cc_works=yes
+  # If we can't run a trivial program, we are probably using a cross compiler.
+  if (./conftest; exit) 2>/dev/null; then
+    ac_cv_prog_cc_cross=no
+  else
+    ac_cv_prog_cc_cross=yes
+  fi
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_cv_prog_cc_works=no
+fi
+rm -fr conftest*
+
+echo "$ac_t""$ac_cv_prog_cc_works" 1>&6
+if test $ac_cv_prog_cc_works = no; then
+  { echo "configure: error: installation or configuration problem: C compiler cannot create executables." 1>&2; exit 1; }
+fi
+echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&6
+echo "configure:2388: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
+echo "$ac_t""$ac_cv_prog_cc_cross" 1>&6
+cross_compiling=$ac_cv_prog_cc_cross
+
+echo $ac_n "checking whether we are using GNU C""... $ac_c" 1>&6
+echo "configure:2393: checking whether we are using GNU C" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_gcc'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.c <<EOF
+#ifdef __GNUC__
+  yes;
+#endif
+EOF
+if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:2402: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
+  ac_cv_prog_gcc=yes
+else
+  ac_cv_prog_gcc=no
+fi
+fi
+
+echo "$ac_t""$ac_cv_prog_gcc" 1>&6
+
+if test $ac_cv_prog_gcc = yes; then
+  GCC=yes
+  ac_test_CFLAGS="${CFLAGS+set}"
+  ac_save_CFLAGS="$CFLAGS"
+  CFLAGS=
+  echo $ac_n "checking whether ${CC-cc} accepts -g""... $ac_c" 1>&6
+echo "configure:2417: checking whether ${CC-cc} accepts -g" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_cc_g'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  echo 'void f(){}' > conftest.c
+if test -z "`${CC-cc} -g -c conftest.c 2>&1`"; then
+  ac_cv_prog_cc_g=yes
+else
+  ac_cv_prog_cc_g=no
+fi
+rm -f conftest*
+
+fi
+
+echo "$ac_t""$ac_cv_prog_cc_g" 1>&6
+  if test "$ac_test_CFLAGS" = set; then
+    CFLAGS="$ac_save_CFLAGS"
+  elif test $ac_cv_prog_cc_g = yes; then
+#    CFLAGS="-g -O2"
+    CFLAGS="-g"
+  else
+#    CFLAGS="-O2"
+    CFLAGS=""
+  fi
+else
+  GCC=
+  test "${CFLAGS+set}" = set || CFLAGS="-g"
+fi
+
+CFLAGS="$pbs_save_CFLAGS"
+
+if test -z "$CFLAGS"; then
+        if   test "$GCC" = "yes"; then
+#    CFLAGS="-g -O2"
+    CFLAGS="-g"
+  elif test "$CC" = "xlc"; then
+    CFLAGS="-O3 -qstrict -qnoansialias -qlibansi -qinfo -qro -qmaxmem=20000"
+  else
+    case "$canonical" in
+      *-*-irix*) CFLAGS='-O -Wl,-woff,84' ;;
+      *-*-hpux*) CFLAGS='-Ae' ;;
+      *-*-osf*)  CFLAGS='-std1' ;;
+      *-*-solaris2.7) if test -n "`isainfo -kv | grep 64-bit`" ; then
+			CFLAGS=-xarch=v9
+		      else
+			CFLAGS=-O
+		      fi ;;
+      *)	 CFLAGS="-O" ;;     esac
+  fi
+fi
+
+
+# figure out the name of "lib" on this system
+# Warning! this is really hacky
+libsuff=
+case $host_os in
+linux-gnu*)
+  case "$host_cpu" in
+  x86_64*|s390x*)
+    echo '#line 819 "configure"' > conftest.$ac_ext
+    echo $ac_n "checking name of lib directory""... $ac_c" 1>&6
+    if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+      case `/usr/bin/file conftest.o` in
+      *64-bit*)
+        libsuff=64
+        ;;
+      esac
+    fi
+    rm -rf conftest*
+    echo "$ac_t""lib$libsuff" 1>&6
+    ;;
+  esac
+esac
+
+
 
 #
 # the default is to build all the executables but not the documents
@@ -958,7 +1201,7 @@ tclx_dir=no
 ac_LL_PATH=`echo "$PATH" | sed -e 's/:/ /g'`
 for ac_libpath in $ac_LL_PATH /__XqqFrobozz ; do
     ac_libpath=`echo $ac_libpath | sed -e 's;/bin$;;'`
-    if test `/bin/ls ${ac_libpath}/lib/libtclx*.* 2> /dev/null | wc -l` -gt 0; then
+    if test `/bin/ls ${ac_libpath}/lib$libsuff/libtclx*.* 2> /dev/null | wc -l` -gt 0; then
         tclx_dir="$ac_libpath"
 	break;
     fi
@@ -993,7 +1236,7 @@ tcl_dir=no
 ac_LL_PATH=`echo "$PATH" | sed -e 's/:/ /g'`
 for ac_libpath in $ac_LL_PATH /__XqqFrobozz ; do
     ac_libpath=`echo $ac_libpath | sed -e 's;/bin$;;'`
-    if test `/bin/ls ${ac_libpath}/lib/libtcl*.* 2> /dev/null | wc -l` -gt 0; then
+    if test `/bin/ls ${ac_libpath}/lib$libsuff/libtcl*.* 2> /dev/null | wc -l` -gt 0; then
         tcl_dir="$ac_libpath"
 	break;
     fi
@@ -1010,7 +1253,7 @@ tcl_dir=no
 ac_LL_PATH=`echo "$PATH" | sed -e 's/:/ /g'`
 for ac_libpath in $ac_LL_PATH /__XqqFrobozz ; do
     ac_libpath=`echo $ac_libpath | sed -e 's;/bin$;;'`
-    if test `/bin/ls ${ac_libpath}/lib/libtcl*.* 2> /dev/null | wc -l` -gt 0; then
+    if test `/bin/ls ${ac_libpath}/lib$libsuff/libtcl*.* 2> /dev/null | wc -l` -gt 0; then
         tcl_dir="$ac_libpath"
 	break;
     fi
@@ -1022,7 +1265,7 @@ if test "$tcl_dir" != no; then
     TCL=1
     TCL_DIR="$tcl_dir"
 
-                    count=`/bin/ls ${tcl_dir}/lib/libtk* 2> /dev/null | wc -l`
+                    count=`/bin/ls ${tcl_dir}/lib$libsuff/libtk* 2> /dev/null | wc -l`
     if test "$count" -gt 0 -a -n "$GUI"; then
 	TK=1
     fi
@@ -1069,10 +1312,10 @@ echo "$ac_t""$pbs_cv_ver_tcl" 1>&6
 	{ echo "configure: error: cannot find Tcl version in $tcl_h" 1>&2; exit 1; };
 
                         TCL_LIB_VER="$TCL_VER"
-    count=`/bin/ls -d $TCL_DIR/lib/libtcl${TCL_LIB_VER}.* 2> /dev/null | wc -l`
+    count=`/bin/ls -d $TCL_DIR/lib$libsuff/libtcl${TCL_LIB_VER}.* 2> /dev/null | wc -l`
     if test "$count" -lt 1; then
         TCL_LIB_VER=`echo $TCL_LIB_VER | sed -e 's/\.//'`
-        count=`/bin/ls $TCL_DIR/lib/libtcl${TCL_LIB_VER}.* | wc -l`
+        count=`/bin/ls $TCL_DIR/lib$libsuff/libtcl${TCL_LIB_VER}.* | wc -l`
         if test "$count" -lt 1; then
             { echo "configure: error: cannot find a Tcl library for version $TCL_VER" 1>&2; exit 1; }
         fi
@@ -1110,10 +1353,10 @@ echo "$ac_t""$pbs_cv_ver_tk" 1>&6
 	{ echo "configure: error: cannot find Tk version in $tk_h" 1>&2; exit 1; };
 
                         TK_LIB_VER="$TK_VER"
-    count=`/bin/ls $TCL_DIR/lib/libtk${TK_LIB_VER}.* 2> /dev/null | wc -l`
+    count=`/bin/ls $TCL_DIR/lib$libsuff/libtk${TK_LIB_VER}.* 2> /dev/null | wc -l`
     if test "$count" -lt 1; then
         TK_LIB_VER=`echo $TK_LIB_VER | sed -e 's/\.//'`
-        count=`/bin/ls $TCL_DIR/lib/libtk${TK_LIB_VER}.* | wc -l`
+        count=`/bin/ls $TCL_DIR/lib$libsuff/libtk${TK_LIB_VER}.* | wc -l`
         if test "$count" -lt 1; then
             { echo "configure: error: cannot find a Tk library for version $TK_VER" 1>&2; exit 1; }
         fi
@@ -1124,19 +1367,57 @@ fi
 
 TCL_LIBS=""; TCL_INCS=""
 
+TCLX_VER=""
 if test "$TCLX" -eq 1; then
 
+
+                    tclx_h=/dev/null
+    for i in $TCL_DIR/include/tclExtend.h \
+      `/bin/ls -d $TCL_DIR/include/tk*/tclExtend.h 2> /dev/null`; do
+        test -r $i && { tclx_h="$i"; break; }
+    done
+
+    echo $ac_n "checking TclX version""... $ac_c" 1>&6
+echo "configure:1057: checking TclX version" >&5
+if eval "test \"`echo '$''{'pbs_cv_ver_tclx'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+        if grep "[ \	]TCLX_VERSION[ \	]" $tclx_h > /dev/null 2>&1; then
+           pbs_cv_ver_tclx=`sed -n \
+               -e 's/.*#define.*TCLX_VERSION[^"]*"\([^"]*\).*/\1/p' \
+               $tclx_h | tail -1`
+        else
+            pbs_cv_ver_tclx=notfound
+    fi
+fi
+
+echo "$ac_t""$pbs_cv_ver_tclx" 1>&6
+
+    TCLX_VER="$pbs_cv_ver_tclx"
+    test "$TCLX_VER" = notfound && \
+	{ echo "configure: error: cannot find TclX version in $tclx_h" 1>&2; exit 1; };
+
+                        TCLX_LIB_VER="$TCLX_VER"
+    count=`/bin/ls $TCL_DIR/lib$libsuff/libtclx${TCLX_LIB_VER}.* 2> /dev/null | wc -l`
+    if test "$count" -lt 1; then
+        TCLX_LIB_VER=`echo $TCLX_LIB_VER | sed -e 's/\.//'`
+        count=`/bin/ls $TCL_DIR/lib$libsuff/libtk${TCLX_LIB_VER}.* | wc -l`
+        if test "$count" -lt 1; then
+            { echo "configure: error: cannot find a TclX library for version $TCLX_VER" 1>&2; exit 1; }
+        fi
+    fi
                 TCLX_DIR="$tclx_dir"
-    TCL_LIBS=$TCL_LIBS' -L$(TCLX_DIR)/lib'
+    TCL_LIBS=$TCL_LIBS' -L$(TCLX_DIR)/lib'$libsuff
     TCL_INCS=$TCL_INCS' -I$(TCLX_DIR)/include'
-    TCL_LIBS=$TCL_LIBS' -ltclx -ltkx'
+    TCL_LIBS="$TCL_LIBS -ltclx${TCLX_LIB_VER} -ltkx${TCLX_LIB_VER}"
 fi
 
 if test "$TCL" -eq 1; then
     TCL_DIR="$tcl_dir"
 
                         if test "$tcl_dir" != "$tclx_dir"; then
-        TCL_LIBS=$TCL_LIBS' -L$(TCL_DIR)/lib'
+        TCL_LIBS=$TCL_LIBS' -L$(TCL_DIR)/lib'$libsuff
     fi
 
                         count=`/bin/ls -d ${tcl_dir}/include/tcl${TCL_VER} 2> /dev/null | wc -l`
@@ -1305,12 +1586,12 @@ if test "$x_libraries" != "NONE" ; then
     echo "configure: warning: "X11 libraries not found"" 1>&2
   fi
 else
-  count=`/bin/ls /usr/lib/libX11* 2> /dev/null | wc -l`
+  count=`/bin/ls /usr/lib$libsuff/libX11* 2> /dev/null | wc -l`
   if test "$count" -eq 0 ; then
     for d in /usr/X11R6 /usr/local /usr/X11R5 ; do
-      count=`/bin/ls $d/lib/libX11* 2> /dev/null | wc -l`
+      count=`/bin/ls $d/lib$libsuff/libX11* 2> /dev/null | wc -l`
       if test "$count" -gt 0 ; then
-        X11LIB="-L$d/lib"
+        X11LIB="-L$d/lib$libsuff"
         break
       fi
     done
@@ -1324,26 +1605,6 @@ fi
 
 
 
-
-
-user_set_cc_val=no
-
-# Check whether --set-cc was given.
-if test "${set_cc+zzq}" = zzq; then
-  setval="$set_cc"
-  CC="${setval}"; user_set_cc_val=yes
-fi
-test "$CC" = yes && { CC=cc; user_set_cc_val=no; }
-
-
-# Check whether --set-cflags was given.
-if test "${set_cflags+zzq}" = zzq; then
-  setval="$set_cflags"
-  cflags="${setval}"
-else
-  cflags="not_set"
-fi
-test "$cflags" = yes && cflags=""
 
 
 # Check whether --enable-debug or --disable-debug was given.
@@ -2470,202 +2731,6 @@ else
 fi
 
 
-
-test "$cflags" = not_set || CFLAGS="$cflags"
-pbs_save_CFLAGS="$CFLAGS"
-# Extract the first word of "gcc", so it can be a program name with args.
-set dummy gcc; ac_word=$2
-echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2277: checking for $ac_word" >&5
-if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  if test -n "$CC"; then
-  ac_cv_prog_CC="$CC" # Let the user override the test.
-else
-  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
-  for ac_dir in $PATH; do
-    test -z "$ac_dir" && ac_dir=.
-    if test -f $ac_dir/$ac_word; then
-      ac_cv_prog_CC="gcc"
-      break
-    fi
-  done
-  IFS="$ac_save_ifs"
-fi
-fi
-CC="$ac_cv_prog_CC"
-if test -n "$CC"; then
-  echo "$ac_t""$CC" 1>&6
-else
-  echo "$ac_t""no" 1>&6
-fi
-
-if test -z "$CC"; then
-  # Extract the first word of "cc", so it can be a program name with args.
-set dummy cc; ac_word=$2
-echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2306: checking for $ac_word" >&5
-if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  if test -n "$CC"; then
-  ac_cv_prog_CC="$CC" # Let the user override the test.
-else
-  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
-  ac_prog_rejected=no
-  for ac_dir in $PATH; do
-    test -z "$ac_dir" && ac_dir=.
-    if test -f $ac_dir/$ac_word; then
-      if test "$ac_dir/$ac_word" = "/usr/ucb/cc"; then
-        ac_prog_rejected=yes
-	continue
-      fi
-      ac_cv_prog_CC="cc"
-      break
-    fi
-  done
-  IFS="$ac_save_ifs"
-if test $ac_prog_rejected = yes; then
-  # We found a bogon in the path, so make sure we never use it.
-  set dummy $ac_cv_prog_CC
-  shift
-  if test $# -gt 0; then
-    # We chose a different compiler from the bogus one.
-    # However, it has the same basename, so the bogon will be chosen
-    # first if we set CC to just the basename; use the full file name.
-    shift
-    set dummy "$ac_dir/$ac_word" "$@"
-    shift
-    ac_cv_prog_CC="$@"
-  fi
-fi
-fi
-fi
-CC="$ac_cv_prog_CC"
-if test -n "$CC"; then
-  echo "$ac_t""$CC" 1>&6
-else
-  echo "$ac_t""no" 1>&6
-fi
-
-  test -z "$CC" && { echo "configure: error: no acceptable cc found in \$PATH" 1>&2; exit 1; }
-fi
-
-echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works""... $ac_c" 1>&6
-echo "configure:2354: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
-
-ac_ext=c
-# CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='${CC-cc} -c $CFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
-ac_link='${CC-cc} -o conftest $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
-cross_compiling=$ac_cv_prog_cc_cross
-
-cat > conftest.$ac_ext <<EOF
-#line 2364 "configure"
-#include "confdefs.h"
-main(){return(0);}
-EOF
-if { (eval echo configure:2368: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
-  ac_cv_prog_cc_works=yes
-  # If we can't run a trivial program, we are probably using a cross compiler.
-  if (./conftest; exit) 2>/dev/null; then
-    ac_cv_prog_cc_cross=no
-  else
-    ac_cv_prog_cc_cross=yes
-  fi
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  ac_cv_prog_cc_works=no
-fi
-rm -fr conftest*
-
-echo "$ac_t""$ac_cv_prog_cc_works" 1>&6
-if test $ac_cv_prog_cc_works = no; then
-  { echo "configure: error: installation or configuration problem: C compiler cannot create executables." 1>&2; exit 1; }
-fi
-echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&6
-echo "configure:2388: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
-echo "$ac_t""$ac_cv_prog_cc_cross" 1>&6
-cross_compiling=$ac_cv_prog_cc_cross
-
-echo $ac_n "checking whether we are using GNU C""... $ac_c" 1>&6
-echo "configure:2393: checking whether we are using GNU C" >&5
-if eval "test \"`echo '$''{'ac_cv_prog_gcc'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  cat > conftest.c <<EOF
-#ifdef __GNUC__
-  yes;
-#endif
-EOF
-if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:2402: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
-  ac_cv_prog_gcc=yes
-else
-  ac_cv_prog_gcc=no
-fi
-fi
-
-echo "$ac_t""$ac_cv_prog_gcc" 1>&6
-
-if test $ac_cv_prog_gcc = yes; then
-  GCC=yes
-  ac_test_CFLAGS="${CFLAGS+set}"
-  ac_save_CFLAGS="$CFLAGS"
-  CFLAGS=
-  echo $ac_n "checking whether ${CC-cc} accepts -g""... $ac_c" 1>&6
-echo "configure:2417: checking whether ${CC-cc} accepts -g" >&5
-if eval "test \"`echo '$''{'ac_cv_prog_cc_g'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  echo 'void f(){}' > conftest.c
-if test -z "`${CC-cc} -g -c conftest.c 2>&1`"; then
-  ac_cv_prog_cc_g=yes
-else
-  ac_cv_prog_cc_g=no
-fi
-rm -f conftest*
-
-fi
-
-echo "$ac_t""$ac_cv_prog_cc_g" 1>&6
-  if test "$ac_test_CFLAGS" = set; then
-    CFLAGS="$ac_save_CFLAGS"
-  elif test $ac_cv_prog_cc_g = yes; then
-#    CFLAGS="-g -O2"
-    CFLAGS="-g"
-  else
-#    CFLAGS="-O2"
-    CFLAGS=""
-  fi
-else
-  GCC=
-  test "${CFLAGS+set}" = set || CFLAGS="-g"
-fi
-
-CFLAGS="$pbs_save_CFLAGS"
-
-if test -z "$CFLAGS"; then
-        if   test "$GCC" = "yes"; then
-#    CFLAGS="-g -O2"
-    CFLAGS="-g"
-  elif test "$CC" = "xlc"; then
-    CFLAGS="-O3 -qstrict -qnoansialias -qlibansi -qinfo -qro -qmaxmem=20000"
-  else
-    case "$canonical" in
-      *-*-irix*) CFLAGS='-O -Wl,-woff,84' ;;
-      *-*-hpux*) CFLAGS='-Ae' ;;
-      *-*-osf*)  CFLAGS='-std1' ;;
-      *-*-solaris2.7) if test -n "`isainfo -kv | grep 64-bit`" ; then
-			CFLAGS=-xarch=v9
-		      else
-			CFLAGS=-O
-		      fi ;;
-      *)	 CFLAGS="-O" ;;     esac
-  fi
-fi
 
 
 MOM_CHECKPOINT=0
