add --with-cpa-lib and --with-cpa-include

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1077,6 +1077,8 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-pic              try to use only PIC/non-PIC objects default=use both
+  --with-cpa-include=DIR  include path for cpalib.h
+  --with-cpa-lib=DIR      lib path for libcpalib
   --without-readline      do not include readline support
                           (default: included if found)
   --with-sched=TYPE       sets the scheduler type. If TYPE is
@@ -5007,7 +5009,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5010 "configure"' > conftest.$ac_ext
+  echo '#line 5012 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5536,7 +5538,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5539: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5541: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6720,7 +6722,7 @@ linux-gnu*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*)
-    echo '#line 6723 "configure"' > conftest.$ac_ext
+    echo '#line 6725 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7392,7 +7394,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7395 "configure"
+#line 7397 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7490,7 +7492,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7493 "configure"
+#line 7495 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8224,7 +8226,7 @@ case $host_os in
   linux-gnu*)
   case "$host_cpu" in
   powerpc*|ppc*)
-    echo '#line 8227 "configure"' > conftest.$ac_ext
+    echo '#line 8229 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8774,13 +8776,11 @@ fi
 
 
 
-
 for ac_header in arpa/inet.h fcntl.h float.h limits.h malloc.h netdb.h \
 		  netinet/in.h stddef.h sys/file.h sys/param.h \
 		  sys/socket.h sys/time.h sys/ioctl.h sys/mount.h \
                   sys/vfs.h sys/statfs.h sys/statvfs.h syslog.h \
-                  termios.h err.h sys/poll.h security/pam_modules.h \
-                  cpalib.h
+                  termios.h err.h sys/poll.h security/pam_modules.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -10109,94 +10109,190 @@ else
 fi;
 echo "$as_me:$LINENO: result: $CPA" >&5
 echo "${ECHO_T}$CPA" >&6
+
+
+# Check whether --with-cpa_include or --without-cpa_include was given.
+if test "${with_cpa_include+set}" = set; then
+  withval="$with_cpa_include"
+  cpainclude=$withval
+else
+  cpainclude=none
+fi;
+
+# Check whether --with-cpa_lib or --without-cpa_lib was given.
+if test "${with_cpa_lib+set}" = set; then
+  withval="$with_cpa_lib"
+  cpalib=$withval
+else
+  cpalib=none
+fi;
+
+if test "x$cpainclude" != "xnone" ;then
+  CPPFLAGS="$CPPFLAGS -I$cpainclude"
+fi
+LDFLAGS_cpasave="$LDFLAGS"
+if test "x$cpalib" != "xnone" ;then
+  LDFLAGS="$LDFLAGS -L$cpalib"
+fi
 case "$CPA" in
   yes)
 cat >>confdefs.h <<\_ACEOF
 #define ENABLE_CPA 1
 _ACEOF
 
-    echo "$as_me:$LINENO: checking for cpa_lookup_nodes" >&5
-echo $ECHO_N "checking for cpa_lookup_nodes... $ECHO_C" >&6
-if test "${ac_cv_func_cpa_lookup_nodes+set}" = set; then
+
+for ac_header in cpalib.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
 else
-  cat >conftest.$ac_ext <<_ACEOF
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-/* System header to define __stub macros and hopefully few prototypes,
-    which can conflict with char cpa_lookup_nodes (); below.
-    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
-    <limits.h> exists even on freestanding compilers.  */
-#ifdef __STDC__
-# include <limits.h>
-#else
-# include <assert.h>
-#endif
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-{
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char cpa_lookup_nodes ();
-/* The GNU C library defines this for functions which it implements
-    to always fail with ENOSYS.  Some functions are actually named
-    something starting with __ and the normal name is an alias.  */
-#if defined (__stub_cpa_lookup_nodes) || defined (__stub___cpa_lookup_nodes)
-choke me
-#else
-char (*f) () = cpa_lookup_nodes;
-#endif
-#ifdef __cplusplus
-}
-#endif
-
-int
-main ()
-{
-return f != cpa_lookup_nodes;
-  ;
-  return 0;
-}
+$ac_includes_default
+#include <$ac_header>
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
+         { ac_try='test -s conftest.$ac_objext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_func_cpa_lookup_nodes=yes
+  ac_header_compiler=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_func_cpa_lookup_nodes=no
+ac_header_compiler=no
 fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
 fi
-echo "$as_me:$LINENO: result: $ac_cv_func_cpa_lookup_nodes" >&5
-echo "${ECHO_T}$ac_cv_func_cpa_lookup_nodes" >&6
-if test $ac_cv_func_cpa_lookup_nodes = yes; then
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
   :
 else
-  echo "$as_me:$LINENO: checking for cpa_lookup_nodes in -lcpa" >&5
-echo $ECHO_N "checking for cpa_lookup_nodes in -lcpa... $ECHO_C" >&6
-if test "${ac_cv_lib_cpa_cpa_lookup_nodes+set}" = set; then
+  { { echo "$as_me:$LINENO: error: pass the path to cpalib.h to --with-cpa-include" >&5
+echo "$as_me: error: pass the path to cpalib.h to --with-cpa-include" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+done
+
+    echo "$as_me:$LINENO: checking for cpa_new_node_req in -lcpalib" >&5
+echo $ECHO_N "checking for cpa_new_node_req in -lcpalib... $ECHO_C" >&6
+if test "${ac_cv_lib_cpalib_cpa_new_node_req+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lcpa  $LIBS"
+LIBS="-lcpalib  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -10211,11 +10307,11 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char cpa_lookup_nodes ();
+char cpa_new_node_req ();
 int
 main ()
 {
-cpa_lookup_nodes ();
+cpa_new_node_req ();
   ;
   return 0;
 }
@@ -10232,34 +10328,38 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_cpa_cpa_lookup_nodes=yes
+  ac_cv_lib_cpalib_cpa_new_node_req=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_cpa_cpa_lookup_nodes=no
+ac_cv_lib_cpalib_cpa_new_node_req=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_cpa_cpa_lookup_nodes" >&5
-echo "${ECHO_T}$ac_cv_lib_cpa_cpa_lookup_nodes" >&6
-if test $ac_cv_lib_cpa_cpa_lookup_nodes = yes; then
-  MOMLIBS="$MOMLIBS -lcpa"
+echo "$as_me:$LINENO: result: $ac_cv_lib_cpalib_cpa_new_node_req" >&5
+echo "${ECHO_T}$ac_cv_lib_cpalib_cpa_new_node_req" >&6
+if test $ac_cv_lib_cpalib_cpa_new_node_req = yes; then
+   :
 else
-  { { echo "$as_me:$LINENO: error: cpa functions are missing" >&5
-echo "$as_me: error: cpa functions are missing" >&2;}
+  { { echo "$as_me:$LINENO: error: pass the path to libcpalib to --with-cpa-lib" >&5
+echo "$as_me: error: pass the path to libcpalib to --with-cpa-lib" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-fi
- ;;
+      if test "x$cpalib" != "xnone" ;then
+        MOMLIBS="$MOMLIBS -L$cpalib -lcpalib"
+      else
+        MOMLIBS="$MOMLIBS -lcpalib"
+      fi
+      ;;
   no) : ;;
   *) { { echo "$as_me:$LINENO: error: --enable-cpa should be yes or no" >&5
 echo "$as_me: error: --enable-cpa should be yes or no" >&2;}
    { (exit 1); exit 1; }; } ;;
 esac
-
+LDFLAGS="$LDFLAGS_cpasave"
 
 
 
