TRQ-3254 - Change pbs_mom init script return codes for status action

diff --git a/contrib/init.d/pbs_mom.in b/contrib/init.d/pbs_mom.in
--- a/contrib/init.d/pbs_mom.in
+++ b/contrib/init.d/pbs_mom.in
@@ -132,12 +132,11 @@ case "$1" in
 			pid=-1
 		fi
 
-		echo "DEBUG: pid = $pid"
-
-		[ $pid -eq -1 -a $lock_present -eq 0 ] && echo -n "pbs_mom dead but subsys locked" && failure && echo && exit 1
-		[ $pid -eq -1 ] && echo -n "pbs_mom already stopped" && success && echo && exit 0
+                # Return codes per Linux Standard Base (LSB) Core Specificiation 3.1
+		[ $pid -eq -1 -a $lock_present -eq 0 ] && echo -n "pbs_mom dead but subsys locked" && failure && echo && exit 2
+		[ $pid -eq -1 ] && echo -n "pbs_mom already stopped" && success && echo && exit 3
 		[ $pid -ne -1 -a $lock_present -eq 0 ] && echo -n "pbs_mom already running" && success && echo && exit 0
-		[ $pid -ne -1 ] && echo -n "pbs_mom running but subsys not locked" && failure && echo && exit 1
+		[ $pid -ne -1 ] && echo -n "pbs_mom running but subsys not locked" && failure && echo && exit 0
 		;;
 	restart)
 		$0 stop
