Support condrestart as used in rpm postinstall scripts during update

diff --git a/contrib/init.d/pbs_mom.in b/contrib/init.d/pbs_mom.in
--- a/contrib/init.d/pbs_mom.in
+++ b/contrib/init.d/pbs_mom.in
@@ -132,7 +132,7 @@ case "$1" in
 			pid=-1
 		fi
 
-                # Return codes per Linux Standard Base (LSB) Core Specificiation 3.1
+		# Return codes per Linux Standard Base (LSB) Core Specificiation 3.1
 		[ $pid -eq -1 -a $lock_present -eq 0 ] && echo -n "pbs_mom dead but subsys locked" && failure && echo && exit 2
 		[ $pid -eq -1 ] && echo -n "pbs_mom already stopped" && success && echo && exit 3
 		[ $pid -ne -1 -a $lock_present -eq 0 ] && echo -n "pbs_mom already running" && success && echo && exit 0
@@ -142,6 +142,10 @@ case "$1" in
 		$0 stop
 		sleep 1
 		$0 start
+		;;
+	condrestart)
+		$0 status || exit 0
+		$0 restart
 		;;
 	reload)
 		echo -n "Re-reading TORQUE Mom config file: "
